name: main workflow

on:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: hack_js
        uses: PocAccount2/hack_js@v3
        with:
          node_version: '20'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
