name: main workflow

on:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: PocAccount2/hack_js@v2
        with:
          node_version: '20'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}